name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Tests on ${{ matrix.go-version }} ${{ matrix.platform }}
    strategy:
      matrix:
        go-version: ['1.22', '1.23']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: make test
    # - uses: codecov/codecov-action@v1
    #   env:
    #     OS: ${{ matrix.platform }}
    #     GO: ${{ matrix.go-version }}
    #   with:
    #     files: ./c.out
    #     env_vars: OS,GO
    # - run: echo "GOPATH=$(go env GOPATH)" >>"$GITHUB_ENV"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
      - run: make lint
        
