name: V8 Build

on: workflow_dispatch

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        name: Build V8 for ${{ matrix.platform }} ${{ matrix.arch }}
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-20.04]
                arch: [x86_64, arm64]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v5
              with:
                  submodules: true
                  fetch-depth: 1
            - run: cd deps/depot_tools && git config --unset-all remote.origin.fetch; git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
              shell: bash
            - if: matrix.platform == 'ubuntu-20.04' && matrix.arch == 'arm64'
              run: sudo apt update && sudo apt install g++-aarch64-linux-gnu -y
            - if: matrix.platform == 'ubuntu-20.04'
              run: cd deps && ./build.py --no-clang --arch ${{ matrix.arch }}
            - if: matrix.platform == 'macos-14'
              run: cd deps && ./build.py --arch ${{ matrix.arch }}
            - uses: peter-evans/create-pull-request@v7
              with:
                commit-message: Update V8 static library for ${{ matrix.platform }} ${{ matrix.arch }}
                branch-suffix: random
                delete-branch: true
                title: V8 static library for ${{ matrix.platform }} ${{ matrix.arch }}
                body: Auto-generated pull request to build V8 for ${{ matrix.platform }} ${{ matrix.arch }}
